#!/bin/bash

# Function to clean up and terminate the script
cleanup() {
    echo "Deleting PID file and terminating the script..."
    rm -f /var/run/myscript.pid
    exit 0
}

# Function to handle SIGTERM and SIGQUIT signals
trap "cleanup" SIGTERM SIGQUIT

# Function to handle SIGINT signal
trap "echo 'Y U no love me?!'" SIGINT

# Function to handle SIGTERM signal
trap "echo 'I hate the kill command'" SIGTERM

# Create a PID file
echo $$ > /var/run/myscript.pid

# Infinite loop displaying the message
while true; do
    echo "To infinity and beyond"
    sleep 1
done

